
services:
  app:
    build: .
    container_name: my-node-app
    ports:
      - "4000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://:wXe7ASTJbC04hQ832gHa95DO6Lq1PlyW@free.clusters.zeabur.com:32764

    volumes:
     - .:/app
     - /app/node_modules

    command: ["npm", "start"]

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
