
services:
  app:
    build: .
    container_name: my-node-app
    ports:
      - "4000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
     - .:/app
     - /app/node_modules

    command: ["npm", "start"]

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
